name: jorgesbooks
favicon: null
layout_spectrum: 0.72968
typography_spectrum: 0.0803
title: My reading list
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6984075976070017
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
