name: jorgesbooks
favicon: null
layout_spectrum: 0.72968
typography_spectrum: 0.23505
title: "Jorge's reading list"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#535456'
    - '#878c92'
    - '#b6c1d3'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
